services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nowo\TaskBoardBundle\Bridge\TimeTrack\:
        resource: '../../Bridge/TimeTrack/'

    Nowo\TaskBoardBundle\EventListener\TimeSpentAggregatorListener: ~
